//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", ConfigurationName="WebShop.WebShopPortType")]
    public interface WebShopPortType
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.trion.am/1C/TradeWebShop#WebShop:GetItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WebShop.GetItemResponse> GetItemAsync(WebShop.GetItemRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.trion.am/1C/TradeWebShop#WebShop:GetItemByName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WebShop.GetItemByNameResponse> GetItemByNameAsync(WebShop.GetItemByNameRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.trion.am/1C/TradeWebShop#WebShop:GetItemByBarcode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WebShop.GetItemByBarcodeResponse> GetItemByBarcodeAsync(WebShop.GetItemByBarcodeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.trion.am/1C/TradeWebShop#WebShop:GetItemsForSale", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WebShop.GetItemsForSaleResponse> GetItemsForSaleAsync(WebShop.GetItemsForSaleRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.trion.am/1C/TradeWebShop#WebShop:ItemConfirm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WebShop.ItemConfirmResponse> ItemConfirmAsync(WebShop.ItemConfirmRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.trion.am/1C/TradeWebShop#WebShop:ValidateOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WebShop.ValidateOrderResponse> ValidateOrderAsync(WebShop.ValidateOrderRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.trion.am/1C/TradeWebShop#WebShop:PayOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WebShop.PayOrderResponse> PayOrderAsync(WebShop.PayOrderRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.trion.am/1C/TradeWebShop#WebShop:ExpireOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WebShop.ExpireOrderResponse> ExpireOrderAsync(WebShop.ExpireOrderRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.trion.am/1C/TradeWebShop#WebShop:GetBonusCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WebShop.GetBonusCardResponse> GetBonusCardAsync(WebShop.GetBonusCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.trion.am/1C/TradeWebShop#WebShop:ItemsInQueue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WebShop.ItemsInQueueResponse> ItemsInQueueAsync(WebShop.ItemsInQueueRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.trion.am/1C/TradeWebShop#WebShop:CustomerCreate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WebShop.CustomerCreateResponse> CustomerCreateAsync(WebShop.CustomerCreateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.trion.am/1C/TradeWebShop#WebShop:CustomerUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WebShop.CustomerUpdateResponse> CustomerUpdateAsync(WebShop.CustomerUpdateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.trion.am/1C/TradeWebShop#WebShop:GetCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WebShop.GetCustomerResponse> GetCustomerAsync(WebShop.GetCustomerRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.trion.am/1C/TradeWebShop#WebShop:GetProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WebShop.GetProductResponse> GetProductAsync(WebShop.GetProductRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.trion.am/1C/TradeWebShopObjects")]
    public partial class Item
    {
        
        private string codeField;
        
        private string articleField;
        
        private string nameField;
        
        private string barcodeField;
        
        private string productField;
        
        private string colorField;
        
        private string ageField;
        
        private string size1Field;
        
        private string size2Field;
        
        private string size3Field;
        
        private string sexField;
        
        private System.Nullable<double> priceField;
        
        private System.Nullable<double> price_OldField;
        
        private System.Nullable<double> inStockField;
        
        private System.Nullable<double> discountPercentField;
        
        private string activeField;
        
        private System.Nullable<bool> newField;
        
        private System.Nullable<bool> bonusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Article
        {
            get
            {
                return this.articleField;
            }
            set
            {
                this.articleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Barcode
        {
            get
            {
                return this.barcodeField;
            }
            set
            {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Product
        {
            get
            {
                return this.productField;
            }
            set
            {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string Color
        {
            get
            {
                return this.colorField;
            }
            set
            {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string Age
        {
            get
            {
                return this.ageField;
            }
            set
            {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string Size1
        {
            get
            {
                return this.size1Field;
            }
            set
            {
                this.size1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string Size2
        {
            get
            {
                return this.size2Field;
            }
            set
            {
                this.size2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string Size3
        {
            get
            {
                return this.size3Field;
            }
            set
            {
                this.size3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string Sex
        {
            get
            {
                return this.sexField;
            }
            set
            {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<double> Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<double> Price_Old
        {
            get
            {
                return this.price_OldField;
            }
            set
            {
                this.price_OldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<double> InStock
        {
            get
            {
                return this.inStockField;
            }
            set
            {
                this.inStockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<double> DiscountPercent
        {
            get
            {
                return this.discountPercentField;
            }
            set
            {
                this.discountPercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<bool> New
        {
            get
            {
                return this.newField;
            }
            set
            {
                this.newField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<bool> Bonus
        {
            get
            {
                return this.bonusField;
            }
            set
            {
                this.bonusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.trion.am/1C/TradeWebShopObjects")]
    public partial class Product
    {
        
        private string entityTypeField;
        
        private string codeField;
        
        private string articleField;
        
        private string titleHYField;
        
        private string titleENField;
        
        private string titleRUField;
        
        private string descriptionHYField;
        
        private string descriptionENField;
        
        private string descriptionRUField;
        
        private string brandField;
        
        private string collectionField;
        
        private string materialDescriptionHYField;
        
        private string materialDescriptionENField;
        
        private string materialDescriptionRUField;
        
        private string activeField;
        
        private string[] categoriesField;
        
        private string[] seasonsField;
        
        private string[] productMaterialsField;
        
        private string[] topicsField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntityType
        {
            get
            {
                return this.entityTypeField;
            }
            set
            {
                this.entityTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Article
        {
            get
            {
                return this.articleField;
            }
            set
            {
                this.articleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string TitleHY
        {
            get
            {
                return this.titleHYField;
            }
            set
            {
                this.titleHYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string TitleEN
        {
            get
            {
                return this.titleENField;
            }
            set
            {
                this.titleENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string TitleRU
        {
            get
            {
                return this.titleRUField;
            }
            set
            {
                this.titleRUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string DescriptionHY
        {
            get
            {
                return this.descriptionHYField;
            }
            set
            {
                this.descriptionHYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string DescriptionEN
        {
            get
            {
                return this.descriptionENField;
            }
            set
            {
                this.descriptionENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string DescriptionRU
        {
            get
            {
                return this.descriptionRUField;
            }
            set
            {
                this.descriptionRUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string Brand
        {
            get
            {
                return this.brandField;
            }
            set
            {
                this.brandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string Collection
        {
            get
            {
                return this.collectionField;
            }
            set
            {
                this.collectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string MaterialDescriptionHY
        {
            get
            {
                return this.materialDescriptionHYField;
            }
            set
            {
                this.materialDescriptionHYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string MaterialDescriptionEN
        {
            get
            {
                return this.materialDescriptionENField;
            }
            set
            {
                this.materialDescriptionENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string MaterialDescriptionRU
        {
            get
            {
                return this.materialDescriptionRUField;
            }
            set
            {
                this.materialDescriptionRUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Categories", IsNullable=true, Order=15)]
        public string[] Categories
        {
            get
            {
                return this.categoriesField;
            }
            set
            {
                this.categoriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Seasons", IsNullable=true, Order=16)]
        public string[] Seasons
        {
            get
            {
                return this.seasonsField;
            }
            set
            {
                this.seasonsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProductMaterials", IsNullable=true, Order=17)]
        public string[] ProductMaterials
        {
            get
            {
                return this.productMaterialsField;
            }
            set
            {
                this.productMaterialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Topics", IsNullable=true, Order=18)]
        public string[] Topics
        {
            get
            {
                return this.topicsField;
            }
            set
            {
                this.topicsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=19)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.trion.am/1C/TradeWebShopObjects")]
    public partial class Customer
    {
        
        private string codeField;
        
        private string nameField;
        
        private string emailField;
        
        private string[] phonesField;
        
        private string[] addressField;
        
        private decimal bonusAmountField;
        
        private string webUserStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Phones", IsNullable=true, Order=3)]
        public string[] Phones
        {
            get
            {
                return this.phonesField;
            }
            set
            {
                this.phonesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Address", IsNullable=true, Order=4)]
        public string[] Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal BonusAmount
        {
            get
            {
                return this.bonusAmountField;
            }
            set
            {
                this.bonusAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string WebUserState
        {
            get
            {
                return this.webUserStateField;
            }
            set
            {
                this.webUserStateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.trion.am/1C/TradeWebShopObjects")]
    public partial class BonusCard
    {
        
        private string codeField;
        
        private string ownerCodeField;
        
        private string ownerNameField;
        
        private string ownerEmailField;
        
        private string ownerPhoneField;
        
        private decimal amountField;
        
        private System.Nullable<bool> activeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OwnerCode
        {
            get
            {
                return this.ownerCodeField;
            }
            set
            {
                this.ownerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OwnerName
        {
            get
            {
                return this.ownerNameField;
            }
            set
            {
                this.ownerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OwnerEmail
        {
            get
            {
                return this.ownerEmailField;
            }
            set
            {
                this.ownerEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OwnerPhone
        {
            get
            {
                return this.ownerPhoneField;
            }
            set
            {
                this.ownerPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<bool> Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.trion.am/1C/TradeWebShopObjects")]
    public partial class OrderItems
    {
        
        private string itemCodeField;
        
        private double quantityField;
        
        private System.Nullable<double> priceField;
        
        private System.Nullable<double> discountPercentField;
        
        private System.Nullable<double> discountAmountField;
        
        private System.Nullable<double> amountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ItemCode
        {
            get
            {
                return this.itemCodeField;
            }
            set
            {
                this.itemCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<double> Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<double> DiscountPercent
        {
            get
            {
                return this.discountPercentField;
            }
            set
            {
                this.discountPercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<double> DiscountAmount
        {
            get
            {
                return this.discountAmountField;
            }
            set
            {
                this.discountAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<double> Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.trion.am/1C/TradeWebShopObjects")]
    public partial class WebOrder
    {
        
        private string transactionNumberField;
        
        private string customerCodeField;
        
        private string customerNameField;
        
        private string customerEmailField;
        
        private string customerPhonesField;
        
        private string customerAddressField;
        
        private string shippingAddressField;
        
        private string billingAddressField;
        
        private string bonusCardCodeField;
        
        private OrderItems[] itemsField;
        
        private System.Nullable<double> orderAmountField;
        
        private System.Nullable<double> shippingAmountField;
        
        private System.Nullable<double> totalAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string TransactionNumber
        {
            get
            {
                return this.transactionNumberField;
            }
            set
            {
                this.transactionNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string CustomerCode
        {
            get
            {
                return this.customerCodeField;
            }
            set
            {
                this.customerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CustomerName
        {
            get
            {
                return this.customerNameField;
            }
            set
            {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CustomerEmail
        {
            get
            {
                return this.customerEmailField;
            }
            set
            {
                this.customerEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CustomerPhones
        {
            get
            {
                return this.customerPhonesField;
            }
            set
            {
                this.customerPhonesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CustomerAddress
        {
            get
            {
                return this.customerAddressField;
            }
            set
            {
                this.customerAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ShippingAddress
        {
            get
            {
                return this.shippingAddressField;
            }
            set
            {
                this.shippingAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string BillingAddress
        {
            get
            {
                return this.billingAddressField;
            }
            set
            {
                this.billingAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string BonusCardCode
        {
            get
            {
                return this.bonusCardCodeField;
            }
            set
            {
                this.bonusCardCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items", Order=9)]
        public OrderItems[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<double> OrderAmount
        {
            get
            {
                return this.orderAmountField;
            }
            set
            {
                this.orderAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<double> ShippingAmount
        {
            get
            {
                return this.shippingAmountField;
            }
            set
            {
                this.shippingAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<double> TotalAmount
        {
            get
            {
                return this.totalAmountField;
            }
            set
            {
                this.totalAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetItem", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class GetItemRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public string ItemCode;
        
        public GetItemRequest()
        {
        }
        
        public GetItemRequest(string ItemCode)
        {
            this.ItemCode = ItemCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetItemResponse", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class GetItemResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public bool @return;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=1)]
        public string ErrorDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=2)]
        public WebShop.Item Item;
        
        public GetItemResponse()
        {
        }
        
        public GetItemResponse(bool @return, string ErrorDescription, WebShop.Item Item)
        {
            this.@return = @return;
            this.ErrorDescription = ErrorDescription;
            this.Item = Item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetItemByName", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class GetItemByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public string ItemName;
        
        public GetItemByNameRequest()
        {
        }
        
        public GetItemByNameRequest(string ItemName)
        {
            this.ItemName = ItemName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetItemByNameResponse", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class GetItemByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public bool @return;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=1)]
        public string ErrorDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=2)]
        public WebShop.Item Item;
        
        public GetItemByNameResponse()
        {
        }
        
        public GetItemByNameResponse(bool @return, string ErrorDescription, WebShop.Item Item)
        {
            this.@return = @return;
            this.ErrorDescription = ErrorDescription;
            this.Item = Item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetItemByBarcode", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class GetItemByBarcodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public string ItemBarcode;
        
        public GetItemByBarcodeRequest()
        {
        }
        
        public GetItemByBarcodeRequest(string ItemBarcode)
        {
            this.ItemBarcode = ItemBarcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetItemByBarcodeResponse", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class GetItemByBarcodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public bool @return;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=1)]
        public string ErrorDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=2)]
        public WebShop.Item Item;
        
        public GetItemByBarcodeResponse()
        {
        }
        
        public GetItemByBarcodeResponse(bool @return, string ErrorDescription, WebShop.Item Item)
        {
            this.@return = @return;
            this.ErrorDescription = ErrorDescription;
            this.Item = Item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetItemsForSale", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class GetItemsForSaleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public long MaxCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=1)]
        public bool AutoConfirm;
        
        public GetItemsForSaleRequest()
        {
        }
        
        public GetItemsForSaleRequest(long MaxCount, bool AutoConfirm)
        {
            this.MaxCount = MaxCount;
            this.AutoConfirm = AutoConfirm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetItemsForSaleResponse", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class GetItemsForSaleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public bool @return;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=1)]
        public string ErrorDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Items", Namespace="http://www.trion.am/1C/TradeWebShopObjects", IsNullable=false)]
        public WebShop.Item[] ItemsForSale;
        
        public GetItemsForSaleResponse()
        {
        }
        
        public GetItemsForSaleResponse(bool @return, string ErrorDescription, WebShop.Item[] ItemsForSale)
        {
            this.@return = @return;
            this.ErrorDescription = ErrorDescription;
            this.ItemsForSale = ItemsForSale;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemConfirm", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class ItemConfirmRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public string ItemCode;
        
        public ItemConfirmRequest()
        {
        }
        
        public ItemConfirmRequest(string ItemCode)
        {
            this.ItemCode = ItemCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemConfirmResponse", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class ItemConfirmResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public bool @return;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=1)]
        public string ErrorDescription;
        
        public ItemConfirmResponse()
        {
        }
        
        public ItemConfirmResponse(bool @return, string ErrorDescription)
        {
            this.@return = @return;
            this.ErrorDescription = ErrorDescription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateOrder", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class ValidateOrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public long OrderNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=1)]
        public WebShop.WebOrder WebOrder;
        
        public ValidateOrderRequest()
        {
        }
        
        public ValidateOrderRequest(long OrderNumber, WebShop.WebOrder WebOrder)
        {
            this.OrderNumber = OrderNumber;
            this.WebOrder = WebOrder;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateOrderResponse", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class ValidateOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public bool @return;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=1)]
        public string ErrorDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=2)]
        public WebShop.WebOrder WebOrder;
        
        public ValidateOrderResponse()
        {
        }
        
        public ValidateOrderResponse(bool @return, string ErrorDescription, WebShop.WebOrder WebOrder)
        {
            this.@return = @return;
            this.ErrorDescription = ErrorDescription;
            this.WebOrder = WebOrder;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PayOrder", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class PayOrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public long OrderNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=1)]
        public string PaymentType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=2)]
        public string Authcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=3)]
        public string CardNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=4)]
        public System.DateTime Datetime;
        
        public PayOrderRequest()
        {
        }
        
        public PayOrderRequest(long OrderNumber, string PaymentType, string Authcode, string CardNumber, System.DateTime Datetime)
        {
            this.OrderNumber = OrderNumber;
            this.PaymentType = PaymentType;
            this.Authcode = Authcode;
            this.CardNumber = CardNumber;
            this.Datetime = Datetime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PayOrderResponse", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class PayOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public bool @return;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=1)]
        public string ErrorDescription;
        
        public PayOrderResponse()
        {
        }
        
        public PayOrderResponse(bool @return, string ErrorDescription)
        {
            this.@return = @return;
            this.ErrorDescription = ErrorDescription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExpireOrder", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class ExpireOrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public long OrderNumber;
        
        public ExpireOrderRequest()
        {
        }
        
        public ExpireOrderRequest(long OrderNumber)
        {
            this.OrderNumber = OrderNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExpireOrderResponse", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class ExpireOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public bool @return;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=1)]
        public string ErrorDescription;
        
        public ExpireOrderResponse()
        {
        }
        
        public ExpireOrderResponse(bool @return, string ErrorDescription)
        {
            this.@return = @return;
            this.ErrorDescription = ErrorDescription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBonusCard", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class GetBonusCardRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public string CardCode;
        
        public GetBonusCardRequest()
        {
        }
        
        public GetBonusCardRequest(string CardCode)
        {
            this.CardCode = CardCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBonusCardResponse", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class GetBonusCardResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public bool @return;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=1)]
        public string ErrorDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=2)]
        public WebShop.BonusCard BonusCard;
        
        public GetBonusCardResponse()
        {
        }
        
        public GetBonusCardResponse(bool @return, string ErrorDescription, WebShop.BonusCard BonusCard)
        {
            this.@return = @return;
            this.ErrorDescription = ErrorDescription;
            this.BonusCard = BonusCard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemsInQueue", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class ItemsInQueueRequest
    {
        
        public ItemsInQueueRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ItemsInQueueResponse", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class ItemsInQueueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> @return;
        
        public ItemsInQueueResponse()
        {
        }
        
        public ItemsInQueueResponse(System.Nullable<decimal> @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CustomerCreate", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class CustomerCreateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public WebShop.Customer Customer;
        
        public CustomerCreateRequest()
        {
        }
        
        public CustomerCreateRequest(WebShop.Customer Customer)
        {
            this.Customer = Customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CustomerCreateResponse", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class CustomerCreateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public bool @return;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=1)]
        public string ErrorDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CustomerCode;
        
        public CustomerCreateResponse()
        {
        }
        
        public CustomerCreateResponse(bool @return, string ErrorDescription, string CustomerCode)
        {
            this.@return = @return;
            this.ErrorDescription = ErrorDescription;
            this.CustomerCode = CustomerCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CustomerUpdate", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class CustomerUpdateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public WebShop.Customer Customer;
        
        public CustomerUpdateRequest()
        {
        }
        
        public CustomerUpdateRequest(WebShop.Customer Customer)
        {
            this.Customer = Customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CustomerUpdateResponse", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class CustomerUpdateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public bool @return;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=1)]
        public string ErrorDescription;
        
        public CustomerUpdateResponse()
        {
        }
        
        public CustomerUpdateResponse(bool @return, string ErrorDescription)
        {
            this.@return = @return;
            this.ErrorDescription = ErrorDescription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomer", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class GetCustomerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public string CustomerCode;
        
        public GetCustomerRequest()
        {
        }
        
        public GetCustomerRequest(string CustomerCode)
        {
            this.CustomerCode = CustomerCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerResponse", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class GetCustomerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public bool @return;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=1)]
        public string ErrorDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=2)]
        public WebShop.Customer Customer;
        
        public GetCustomerResponse()
        {
        }
        
        public GetCustomerResponse(bool @return, string ErrorDescription, WebShop.Customer Customer)
        {
            this.@return = @return;
            this.ErrorDescription = ErrorDescription;
            this.Customer = Customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProduct", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class GetProductRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public string ProductCode;
        
        public GetProductRequest()
        {
        }
        
        public GetProductRequest(string ProductCode)
        {
            this.ProductCode = ProductCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductResponse", WrapperNamespace="http://www.trion.am/1C/TradeWebShop", IsWrapped=true)]
    public partial class GetProductResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=0)]
        public bool @return;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=1)]
        public string ErrorDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.trion.am/1C/TradeWebShop", Order=2)]
        public WebShop.Product Product;
        
        public GetProductResponse()
        {
        }
        
        public GetProductResponse(bool @return, string ErrorDescription, WebShop.Product Product)
        {
            this.@return = @return;
            this.ErrorDescription = ErrorDescription;
            this.Product = Product;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface WebShopPortTypeChannel : WebShop.WebShopPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WebShopPortTypeClient : System.ServiceModel.ClientBase<WebShop.WebShopPortType>, WebShop.WebShopPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebShopPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(WebShopPortTypeClient.GetBindingForEndpoint(endpointConfiguration), WebShopPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebShopPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebShopPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebShopPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebShopPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebShopPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<WebShop.GetItemResponse> GetItemAsync(WebShop.GetItemRequest request)
        {
            return base.Channel.GetItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebShop.GetItemByNameResponse> GetItemByNameAsync(WebShop.GetItemByNameRequest request)
        {
            return base.Channel.GetItemByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebShop.GetItemByBarcodeResponse> GetItemByBarcodeAsync(WebShop.GetItemByBarcodeRequest request)
        {
            return base.Channel.GetItemByBarcodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebShop.GetItemsForSaleResponse> GetItemsForSaleAsync(WebShop.GetItemsForSaleRequest request)
        {
            return base.Channel.GetItemsForSaleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebShop.ItemConfirmResponse> ItemConfirmAsync(WebShop.ItemConfirmRequest request)
        {
            return base.Channel.ItemConfirmAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebShop.ValidateOrderResponse> ValidateOrderAsync(WebShop.ValidateOrderRequest request)
        {
            return base.Channel.ValidateOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebShop.PayOrderResponse> PayOrderAsync(WebShop.PayOrderRequest request)
        {
            return base.Channel.PayOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebShop.ExpireOrderResponse> ExpireOrderAsync(WebShop.ExpireOrderRequest request)
        {
            return base.Channel.ExpireOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebShop.GetBonusCardResponse> GetBonusCardAsync(WebShop.GetBonusCardRequest request)
        {
            return base.Channel.GetBonusCardAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebShop.ItemsInQueueResponse> WebShop.WebShopPortType.ItemsInQueueAsync(WebShop.ItemsInQueueRequest request)
        {
            return base.Channel.ItemsInQueueAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebShop.ItemsInQueueResponse> ItemsInQueueAsync()
        {
            WebShop.ItemsInQueueRequest inValue = new WebShop.ItemsInQueueRequest();
            return ((WebShop.WebShopPortType)(this)).ItemsInQueueAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<WebShop.CustomerCreateResponse> CustomerCreateAsync(WebShop.CustomerCreateRequest request)
        {
            return base.Channel.CustomerCreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebShop.CustomerUpdateResponse> CustomerUpdateAsync(WebShop.CustomerUpdateRequest request)
        {
            return base.Channel.CustomerUpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebShop.GetCustomerResponse> GetCustomerAsync(WebShop.GetCustomerRequest request)
        {
            return base.Channel.GetCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebShop.GetProductResponse> GetProductAsync(WebShop.GetProductRequest request)
        {
            return base.Channel.GetProductAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebShopSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebShopSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebShopSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://212.42.214.82:33335/URARTU/ws/WebShop");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebShopSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://212.42.214.82:33335/URARTU/ws/WebShop");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebShopSoap,
            
            WebShopSoap12,
        }
    }
}
